#!/bin/bash


if [ $(id -u) -ne 0 ]; then
    echo "Please run as root"
    exit 1;
fi

systemctl stop wowthing_upload

# copy file
echo "copying wowthing_upload.service to /etc/systemd/system/wowthing_upload.service"
cp ./wowthing_upload.service /etc/systemd/system/wowthing_upload.service

# enable the service
systemctl enable wowthing_upload
systemctl start wowthing_upload

# check status as confirmation
systemctl status wowthing_upload
